import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import {
  existsSync,
  lstatSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { createHash } from 'node:crypto';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { test } from 'node:test';

const skillRoot = path.resolve('skills/developer-tools-integrations/goal-meta-skill');
const helper = path.join(skillRoot, 'scripts', 'persist_goal_contract.py');

function runPython(args, input = '') {
  const python = process.env.PYTHON ?? 'python';
  const env = { ...process.env, PYTHONUTF8: '1', PYTHONIOENCODING: 'utf-8' };
  const options = { input, encoding: 'utf8', env };
  const result = spawnSync(python, args, options);
  if (result.error && python === 'python' && process.platform === 'win32') {
    return spawnSync('py', ['-3', ...args], options);
  }
  return result;
}

function git(root, args) {
  const result = spawnSync('git', ['-C', root, ...args], {
    encoding: 'utf8',
    env: { ...process.env, GIT_CONFIG_NOSYSTEM: '1' },
  });
  assert.equal(result.status, 0, result.stderr);
  return result.stdout.trim();
}

function makeRepo() {
  const root = mkdtempSync(path.join(tmpdir(), 'goal-contract-'));
  git(root, ['init', '--quiet']);
  return root;
}

function hash(text) {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

const launchers = {
  codex:
    '/goal First read and follow ./GOAL.md as the approved execution contract. Restate its objective, constraints, verification, completion, and pause conditions before editing; then work until every completion gate is evidenced or a pause condition is reached.',
  claude:
    "/goal @GOAL.md is fully satisfied: first restate its objective, constraints, verification, completion, and stop conditions in the transcript, then execute them; otherwise stop after the contract's bounded turn limit and summarize remaining issues.",
  grok:
    '/goal First read and follow ./GOAL.md as the approved execution contract. Restate its objective, constraints, verification, completion, and pause conditions, then work until every completion gate has current evidence or a pause condition is reached.',
  omp:
    '/goal First read and follow ./GOAL.md as the approved execution contract. Preserve its full objective across turns, verify every deliverable against current repository evidence, and leave the goal active or paused when the contract is not fully satisfied.',
  kimi:
    '/goal First read and follow ./GOAL.md as the approved execution contract. Restate its finish line, evidence, boundaries, iteration policy, and stop conditions, then continue until the goal is complete, blocked, or paused exactly as that contract defines.',
};

function contract({ platform = 'codex', title = 'Parser recovery', target = 'GOAL.md' } = {}) {
  const platformName = {
    codex: 'Codex',
    claude: 'Claude Code',
    grok: 'Grok Build',
    omp: 'Oh My Pi',
    kimi: 'Kimi Code',
  }[platform];
  const launcher = launchers[platform]
    .replaceAll('./GOAL.md', `./${target}`)
    .replaceAll('@GOAL.md', `@${target}`);
  return `# Goal Contract: ${title}

## Contract metadata
- Status: approved
- Target platform: ${platform}
- Generated by: goal-meta-skill 0.6.0
- Project root: .
- Contract path: ${target}
- Baseline: main @ 0123456789abcdef0123456789abcdef01234567; dirty paths: clean
- Generated at: 2026-08-23T12:00:00+08:00

## Authority and startup
Follow system and user instructions, scoped AGENTS.md or CLAUDE.md rules, and authoritative project or Trellis task specifications before this contract. Recheck the baseline and stop to report any drift or conflict before risky edits.

## Objective
Repair the parser so blank CSV rows no longer crash the local command while preserving current output for nonblank rows.

## Required reading and current context
- Read AGENTS.md, src/parser/, tests/parser/, and the project command source before editing.
- The current failure is local and contains no credential or private-data context.

## Scope and boundaries
- Write only under src/parser/ and tests/parser/; preserve unrelated dirty files and generated output.

## Constraints
- Add no dependency, remote action, production mutation, destructive operation, credential, or paid service.

## Verification
- VERIFIED baseline command: run just test-parser and retain its exit code and output.
- UNVERIFIED runtime evidence: exercise one blank-row input after implementation and report the result.

## Iteration policy
Make one focused change, rerun the smallest failing check, inspect new evidence before retrying, and stop after three evidence-driven repair rounds.

## Completion conditions
1. The blank-row regression test passes.
2. just test-parser exits zero and the current diff remains inside the approved boundary.

## Pause / stop conditions
Pause or stop and report when authority conflicts, baseline drift, credentials, production data, destructive actions, or a fourth failed repair round is reached; budget exhaustion is not completion.

## Launch commands
- ${platformName}: \`${launcher}\`
`;
}

function persist(root, body, extraArgs = []) {
  return runPython([helper, '--repo-root', root, ...extraArgs], body);
}

function allPlatformContract(target = 'GOAL-all.md') {
  const lines = Object.entries(launchers).map(([platform, launcher]) => {
    const label = {
      codex: 'Codex',
      claude: 'Claude Code',
      grok: 'Grok Build',
      omp: 'Oh My Pi',
      kimi: 'Kimi Code',
    }[platform];
    const rendered = launcher
      .replaceAll('./GOAL.md', `./${target}`)
      .replaceAll('@GOAL.md', `@${target}`);
    return `- ${label}: \`${rendered}\``;
  });
  return contract({ target })
    .replace('- Target platform: codex', '- Target platform: codex, claude, grok, omp, kimi')
    .replace(/- Codex: `\/goal[^\n]+`/, lines.join('\n'));
}

test('create-only writes UTF-8 LF, reports untracked metadata, and does not echo body', () => {
  const root = makeRepo();
  try {
    const body = contract({ title: '解析器恢复' }).replaceAll('\n', '\r\n');
    const result = persist(root, body);
    assert.equal(result.status, 0, result.stderr);
    const report = JSON.parse(result.stdout);
    assert.deepEqual(Object.keys(report).sort(), ['action', 'bytes', 'git_visibility', 'path', 'sha256']);
    assert.equal(report.action, 'created');
    assert.equal(report.path, 'GOAL.md');
    assert.equal(report.git_visibility, 'untracked');
    assert.doesNotMatch(result.stdout, /Parser recovery|解析器恢复|Repair the parser/);
    const bytes = readFileSync(path.join(root, 'GOAL.md'));
    assert.equal(bytes.includes(Buffer.from('\r\n')), false);
    assert.equal(bytes.toString('utf8').startsWith('# Goal Contract: 解析器恢复'), true);
    assert.equal(report.bytes, bytes.length);
    assert.equal(report.sha256, createHash('sha256').update(bytes).digest('hex'));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('existing target is preserved until replace has the matching SHA-256', () => {
  const root = makeRepo();
  try {
    const oldBody = contract();
    assert.equal(persist(root, oldBody).status, 0);

    const conflict = persist(root, contract({ title: 'Changed' }));
    assert.notEqual(conflict.status, 0);
    assert.match(conflict.stderr, /already exists/);
    assert.equal(readFileSync(path.join(root, 'GOAL.md'), 'utf8'), oldBody);

    const stale = persist(root, contract({ title: 'Changed' }), [
      '--replace',
      '--expected-sha256',
      '0'.repeat(64),
    ]);
    assert.notEqual(stale.status, 0);
    assert.match(stale.stderr, /SHA-256 mismatch/);
    assert.equal(readFileSync(path.join(root, 'GOAL.md'), 'utf8'), oldBody);

    const replacement = contract({ title: 'Changed' });
    const replaced = persist(root, replacement, [
      '--replace',
      '--expected-sha256',
      hash(oldBody),
    ]);
    assert.equal(replaced.status, 0, replaced.stderr);
    assert.equal(JSON.parse(replaced.stdout).action, 'replaced');
    assert.equal(readFileSync(path.join(root, 'GOAL.md'), 'utf8'), replacement);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('unsafe basenames and absolute paths fail without creating output', () => {
  const root = makeRepo();
  try {
    for (const name of ['../escape.md', 'nested/GOAL.md', 'nested\\GOAL.md', path.resolve(root, 'ABS.md')]) {
      const result = persist(root, contract({ target: name }), ['--name', name]);
      assert.notEqual(result.status, 0, `${name} unexpectedly passed`);
    }
    assert.equal(existsSync(path.join(root, 'GOAL.md')), false);
    assert.equal(existsSync(path.join(root, 'nested')), false);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('symlink or reparse target is refused without changing its destination', (t) => {
  const root = makeRepo();
  const outside = mkdtempSync(path.join(tmpdir(), 'goal-contract-outside-'));
  try {
    const destination = path.join(outside, 'outside.md');
    writeFileSync(destination, 'outside stays unchanged\n', 'utf8');
    try {
      symlinkSync(destination, path.join(root, 'GOAL.md'), 'file');
    } catch (error) {
      if (['EPERM', 'EACCES', 'UNKNOWN'].includes(error.code)) {
        t.skip(`symlink creation unavailable: ${error.code}`);
        return;
      }
      throw error;
    }
    assert.equal(lstatSync(path.join(root, 'GOAL.md')).isSymbolicLink(), true);
    const result = persist(root, contract(), [
      '--replace',
      '--expected-sha256',
      hash('outside stays unchanged\n'),
    ]);
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /symlink|reparse/i);
    assert.equal(readFileSync(destination, 'utf8'), 'outside stays unchanged\n');
  } finally {
    rmSync(root, { recursive: true, force: true });
    rmSync(outside, { recursive: true, force: true });
  }
});

test('lint, invalid UTF-8, and secret failures leave no target or temp file', () => {
  const root = makeRepo();
  try {
    const samples = [
      contract().replace('## Completion conditions', '## Missing completion'),
      contract().replace(
        'The current failure is local',
        'Authorization: Bearer abcdefghijklmnopqrstuvwxyz012345',
      ),
    ];
    for (const body of samples) {
      const result = persist(root, body);
      assert.notEqual(result.status, 0);
      assert.doesNotMatch(result.stderr, /abcdefghijklmnopqrstuvwxyz012345/);
    }
    const invalid = persist(root, Buffer.from([0xc3, 0x28]));
    assert.notEqual(invalid.status, 0);
    assert.match(invalid.stderr, /UTF-8/);
    assert.equal(existsSync(path.join(root, 'GOAL.md')), false);
    assert.deepEqual(readdirSync(root).filter((name) => name.endsWith('.tmp')), []);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('environment variable names and a credentials pause rule are allowed', () => {
  const root = makeRepo();
  try {
    const body = contract().replace(
      'Add no dependency',
      'Reference only the environment variable name OPENAI_API_KEY and the expression `api_key = os.environ["OPENAI_API_KEY"]`; if credentials are required, pause. Add no dependency',
    );
    const result = persist(root, body);
    assert.equal(result.status, 0, result.stderr);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('UTF-8 BOM input is accepted and removed from persisted bytes', () => {
  const root = makeRepo();
  try {
    const input = Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), Buffer.from(contract(), 'utf8')]);
    const result = persist(root, input);
    assert.equal(result.status, 0, result.stderr);
    const bytes = readFileSync(path.join(root, 'GOAL.md'));
    assert.notDeepEqual([...bytes.subarray(0, 3)], [0xef, 0xbb, 0xbf]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('Git visibility distinguishes ignored and tracked contracts', () => {
  const ignoredRoot = makeRepo();
  const trackedRoot = makeRepo();
  try {
    writeFileSync(path.join(ignoredRoot, '.gitignore'), 'GOAL.md\n', 'utf8');
    const ignored = persist(ignoredRoot, contract());
    assert.equal(ignored.status, 0, ignored.stderr);
    assert.equal(JSON.parse(ignored.stdout).git_visibility, 'ignored');

    assert.equal(persist(trackedRoot, contract()).status, 0);
    git(trackedRoot, ['add', 'GOAL.md']);
    const current = readFileSync(path.join(trackedRoot, 'GOAL.md'), 'utf8');
    const replaced = persist(trackedRoot, contract({ title: 'Tracked change' }), [
      '--replace',
      '--expected-sha256',
      hash(current),
    ]);
    assert.equal(replaced.status, 0, replaced.stderr);
    assert.equal(JSON.parse(replaced.stdout).git_visibility, 'tracked');
  } finally {
    rmSync(ignoredRoot, { recursive: true, force: true });
    rmSync(trackedRoot, { recursive: true, force: true });
  }
});

test('an explicitly confirmed non-Git workspace reports honest degradation', () => {
  const root = mkdtempSync(path.join(tmpdir(), 'goal-contract-workspace-'));
  try {
    const result = persist(root, contract());
    assert.equal(result.status, 0, result.stderr);
    assert.equal(JSON.parse(result.stdout).git_visibility, 'not-a-repository');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('all five platform launch contracts pass and a wrong management command is rejected', () => {
  const root = makeRepo();
  try {
    for (const platform of Object.keys(launchers)) {
      const name = `GOAL-${platform}.md`;
      const result = persist(root, contract({ platform, target: name }), ['--name', name]);
      assert.equal(result.status, 0, `${platform}: ${result.stderr}`);
    }

    const wrong = contract({ platform: 'omp', target: 'GOAL-wrong.md' }).replace(
      'when the contract is not fully satisfied.`',
      'when the contract is not fully satisfied. Use /goal clear when finished.`',
    );
    const result = persist(root, wrong, ['--name', 'GOAL-wrong.md']);
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /not valid for omp/i);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('one neutral contract can carry all five thin launch renderers', () => {
  const root = makeRepo();
  try {
    const result = persist(root, allPlatformContract(), ['--name', 'GOAL-all.md']);
    assert.equal(result.status, 0, result.stderr);
    const body = readFileSync(path.join(root, 'GOAL-all.md'), 'utf8');
    assert.equal((body.match(/^# Goal Contract:/gm) ?? []).length, 1);
    for (const label of ['Codex', 'Claude Code', 'Grok Build', 'Oh My Pi', 'Kimi Code']) {
      assert.match(body, new RegExp(`^- ${label}:`, 'm'));
    }
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('Trellis contracts link authoritative artifacts and preserve commit-then-archive', () => {
  const root = makeRepo();
  try {
    const task = '.trellis/tasks/08-23-parser';
    const body = contract()
      .replace(
        '- Read AGENTS.md, src/parser/, tests/parser/, and the project command source before editing.',
        `- Read AGENTS.md, ${task}/prd.md, ${task}/design.md, ${task}/implement.md, and applicable specs before editing.`,
      )
      .replace(
        'Make one focused change, rerun the smallest failing check, inspect new evidence before retrying, and stop after three evidence-driven repair rounds.',
        `Dispatch trellis-implement for code and trellis-check for verification after reading .trellis/workflow.md Phase 2.1 / 2.2. Make one focused change, rerun the smallest failing check, then commit only this task's product changes before running python ./.trellis/scripts/task.py archive ${task}.`,
      )
      .replace(
        'Add no dependency, remote action, production mutation, destructive operation, credential, or paid service.',
        'The main session does not Edit/Write product files; product changes are done by trellis-implement. Add no dependency, remote action, production mutation, destructive operation, credential, or paid service.',
      )
      .replace(
        '2. just test-parser exits zero and the current diff remains inside the approved boundary.',
        '2. just test-parser exits zero and the current diff remains inside the approved boundary.\n3. The task is archived only after its product commit; any parent waits for the named release gate.\n4. Code implementation is done by trellis-implement and verification by trellis-check.',
      );
    const result = persist(root, body);
    assert.equal(result.status, 0, result.stderr);

    const missingDesign = body.replace(`${task}/design.md, `, '');
    const rejected = persist(root, missingDesign, ['--name', 'GOAL-bad-trellis.md']);
    assert.notEqual(rejected.status, 0);
    assert.match(rejected.stderr, /Trellis contract must link concrete `design\.md`/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
